apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 57.152.50.3:8082/poc/my-docker-image:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: artifactory-secret

